### ISSUE TITLE
没有可以带参数的get请求方式

### ISSUE THREAD

**Issue by DukeChina** [fuminwen/Grace#1]
由于封装了请求过程，当想要发送带参数的GET请求时，需要在HttpRequest.url()前拼接好所有的键值对到请求URL中，导致实际上并没有真正简化操作，看看是否能够添加方法来更方便的使用带参数的Get请求

**Comment by fuminwen** [comment]
设计上使用纯URL，不经过urlencode的原始url作为第一形态。GET方式中，提供K-V的方式填充URL的显示参数。
是想自己已经构造好的url-with-kv样式生成请求？
不走统一的封装动作？
